export { BasePage } from './base.page';
export { HomePage } from './home.page';
export { LoginPage } from './login.page';
export { SecureAreaPage } from './secure-area.page';
export { AddRemoveElementsPage } from './add-remove-elements.page';
export { CheckboxesPage } from './checkboxes.page';
export { DropdownPage } from './dropdown.page';
export { JavaScriptAlertsPage } from './javascript-alerts.page';
export { FileUploadPage } from './file-upload.page';